In [1]:
import pandas as pd
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [3]:
df['spam']= df['Category'].apply(lambda x:1 if x=='spam' else 0)
df.drop('Category',axis=1,inplace=True)


In [4]:
df

Message  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
v = CountVectorizer()

In [10]:
X_train_cv = v.fit_transform(X_train.values)

In [11]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59185 stored elements and shape (4457, 7786)>

In [13]:
v.get_feature_names_out()[1771:2000]

array(['chat', 'chat80155', 'chatlines', 'chatter', 'chatting', 'cheap',
       'cheaper', 'cheat', 'cheating', 'chechi', 'check', 'checkboxes',
       'checked', 'checkin', 'checking', 'checkmate', 'checkup', 'cheer',
       'cheered', 'cheers', 'cheery', 'cheese', 'cheesy', 'cheetos',
       'chef', 'chennai', 'cheque', 'cherish', 'cherthala', 'chess',
       'chest', 'chex', 'chez', 'chgs', 'chic', 'chick', 'chicken',
       'chief', 'chik', 'chikku', 'child', 'childish', 'childporn',
       'children', 'childrens', 'chile', 'chill', 'chillin', 'china',
       'chinatown', 'chinchillas', 'chinese', 'chiong', 'chip', 'chit',
       'chk', 'chocolate', 'choice', 'choices', 'choose', 'choosing',
       'chop', 'chords', 'chores', 'chosen', 'chrgd', 'christians',
       'christmas', 'christmassy', 'chuck', 'chuckin', 'church', 'cine',
       'cinema', 'citizen', 'city', 'citylink', 'cl', 'claim',
       'claimcode', 'claims', 'claire', 'clarify', 'clark', 'clas',
       'clash', 'class'

In [14]:
v.vocabulary_

{'shit': 6138,
 'babe': 1202,
 'thasa': 6857,
 'bit': 1387,
 'messed': 4501,
 'up': 7230,
 'yeh': 7729,
 'she': 6115,
 'shudvetold': 6183,
 'did': 2323,
 'urgran': 7255,
 'know': 3998,
 'neway': 4795,
 'illspeak': 3653,
 'u2moro': 7161,
 'wen': 7501,
 'im': 3654,
 'not': 4865,
 'asleep': 1114,
 'you': 7750,
 'call': 1631,
 'times': 6944,
 'job': 3870,
 'today': 6985,
 'ok': 4948,
 'umma': 7178,
 'and': 973,
 'ask': 1107,
 'them': 6871,
 'to': 6978,
 'speed': 6410,
 'if': 3638,
 'have': 3393,
 'belive': 1328,
 'me': 4447,
 'come': 1931,
 'my': 4703,
 'home': 3508,
 'fine': 2883,
 'hope': 3525,
 'are': 1060,
 'good': 3219,
 'do': 2396,
 'take': 6738,
 'care': 1679,
 'shall': 6103,
 'bring': 1533,
 'us': 7261,
 'bottle': 1469,
 'of': 4924,
 'wine': 7575,
 'keep': 3947,
 'amused': 967,
 'only': 4978,
 'joking': 3884,
 'll': 4194,
 'one': 4972,
 'anyway': 1014,
 'private': 5461,
 'your': 7754,
 '2004': 350,
 'account': 793,
 'statement': 6498,
 'for': 2967,
 '07742676969': 27,
 'shows': 617

In [15]:
X_train_cv.shape#4457 emails and 7786 of words/bag of wprds/vocabulary

(4457, 7786)

In [16]:
X_train_np =    X_train_cv.toarray()

In [17]:
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4, 7786))

In [19]:
import numpy as np
np.where(X_train_np[0]!=0)

(array([1114, 1202, 1387, 2323, 3653, 3654, 3998, 4501, 4795, 4865, 6115,
        6138, 6183, 6857, 7161, 7230, 7255, 7501, 7729]),)

In [20]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [21]:
X_test_cv = v.transform(X_test)

In [22]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.96      0.92      0.94       144

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [23]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [24]:
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [25]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])


In [26]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [27]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.96      0.92      0.94       144

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



Exercise